/*  ECE 587 Lab 7: Memory Simulator
 *
 *      Simulates Memory.
 *
 *  Author: Nolan Kitchin
 *    CWID: 11572421
 *    Date: 26 March 2018
 */

#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <math.h>

int mainMem;
int cacheSize;
int cacheBlockSize;
int setAssoc;
char replPolicy[100];
char fileName[100];
FILE *inputFile;

int isNumeric(char* str){
  for(int i = 0; i < strlen(str); i++){
    if(str[i] == '\n'){
      continue;
    }
    if(!isdigit(str[i])){
      return 0;
    }
  }
  return 1;
}

void specifyMemorySpecs(){
  for( ; ; ){
    printf("Enter the size of main memory in bytes: ");
    char memStr[100];
    scanf("%s",memStr);
    if(isNumeric(memStr)){
      mainMem = atoi(memStr);
      if(mainMem < 4 || mainMem > 32768){
        printf("Error! Input out of range. Valid range is 4 to 32768 bytes.\n\n");
      }else{
        break;
      }
    }else{
      printf("Error! Only numeric input is valid.\n\n");
    }
  }

  for( ; ; ){
    printf("Enter the size of the cache in bytes: ");
    char cacheStr[100];
    scanf("%s", cacheStr);
    if(isNumeric(cacheStr)){
      cacheSize = atoi(cacheStr);
      if(cacheSize < 2 || cacheSize >= mainMem){
        printf("Error! Input out of range. Valid range is 2 to %d bytes.\n\n", mainMem-1);
      }else{
        break;
      }
    }else{
      printf("Error! Only numeric input is valid.\n\n");
    }
  }

  for( ; ; ){
    printf("Enter the cache block/line size in bytes: ");
    char blockStr[100];
    scanf("%s", blockStr);
    if(isNumeric(blockStr)){
      cacheBlockSize = atoi(blockStr);
      if(cacheBlockSize < 2 || cacheBlockSize > cacheSize){
        printf("Error! Input out of range. Valid range is 2 to %d bytes.\n\n", cacheSize);
      }else{
        break;
      }
    }else{
      printf("Error! Only numeric input is valid.\n\n");
    }
  }

  for( ; ; ){
    printf("Enter the degree of set-associativity (input n for an n-way set-associative mapping): ");
    char assocStr[100];
    scanf("%s", assocStr);
    if(isNumeric(assocStr)){
      setAssoc = atoi(assocStr);

      //TODO: fix range on setAssoc
      if(setAssoc < 1 || setAssoc > 32768){
        printf("Error! Input out of range. Valid range is 2 to 32768 bytes.\n\n");
      }else{
        break;
      }
    }else{
      printf("Error! Only numeric input is valid.\n\n");
    }
  }

  for( ; ; ){
    printf("Enter the replacement policy (L = LRU, F = FIFO): ");
    scanf("%s", replPolicy);
    if(strcmp(replPolicy, "L") != 0 && strcmp(replPolicy, "F") != 0){
      printf("\nError! Invalid input. Only 'L' or 'F' are acceptable inputs.\n\n");
    }else{
      break;
    }
  }
  return;
}

int intLog2(int base2Num){
  if(base2Num % 2 != 0){
    printf("Error. Only Base 2 numbers or 1 is allowed.\n");
    return -1;
  }else if(base2Num == 1){
    return 0;
  }
  int count = 0;
  while(base2Num > 1){
    base2Num /= 2;
    count++;
  }
  return count;
}

void memCalc(){
  int addrLines = intLog2(mainMem);
  int bitOffset = intLog2(cacheBlockSize);
  int bitIndex = intLog2((cacheSize/cacheBlockSize)/setAssoc);
  int bitTag = addrLines - (bitOffset + bitIndex);
  int totalCacheSize = cacheSize + (bitTag + 2)*(cacheSize / cacheBlockSize)/8;
  printf("\nSimulator Output:\n");
  printf("Total address lines required = %d\n", addrLines);
  printf("Number of bits for offset = %d\n", bitOffset);
  printf("Number of bits for index = %d\n", bitIndex);
  printf("Number of bits for tag = %d\n", bitTag);
  printf("Total cache size required = %d bytes\n", totalCacheSize);
}

void read(int memoryLoc){

}

void write(int memoryLoc){

}

int parseFile(){
  int numMemRef;
  int freePosition = 0;
  printf("Enter the name of the input file containing the list of memory references generated by the CPU: ");
  scanf("%s", fileName);
  errno = 0;
  inputFile = fopen(fileName, "r");
  if(errno == 2){
    perror("\n\nError");
    printf("\n\n");
    errno = 0;
    return 0;
  }else if(errno == 0){
    char memRefStr[100];
    fscanf(inputFile, "%s", memRefStr);
    fgetc(inputFile);
    char newLine[100];
    fgets(newLine, 100, inputFile);
    if(isNumeric(memRefStr)){
      numMemRef = atoi(memRefStr);
      int memRef[numMemRef];
      if(strcmp(newLine,"\n") != 0){
        printf("\n\nError reading file '%s'.  The second line of the input file must be a carriage return.\n\n\n", fileName);
        return 0;
      }
      int referenceCounter = 0;
      while(fgets(newLine, 100, inputFile) != NULL){
        printf("%s", newLine);
        if(newLine[0] == 'R' || newLine[0] == 'W'){
          if(!isspace(newLine[1])){
            printf("\n\nError reading file '%s'.  There must be a space after each 'R' or 'W' after the second line of the file.\n\n", fileName);
            return 0;
          }else{
            char restOfLine[100];
            strcpy(restOfLine, newLine + 2);
            if(!isNumeric(restOfLine)){
              printf("\n\nError reading file '%s'.  Memory locations must be numeric.\n\n\n", fileName);
              return 0;
            }else{
              int memLoc = atoi(restOfLine);
              memRef[freePosition] = memLoc;
              freePosition++;
              if(memLoc < 0 || memLoc > mainMem - 1){
                printf("\n\nError reading file '%s'.  %d is out of range.  Valid memory addresses range from 0 to %d \n\n", fileName, memLoc, mainMem-1);
                return 0;
              }else{
                if(newLine[0] == 'R'){
                  read(memLoc);
                }else if(newLine[0] == 'W'){
                  write(memLoc);
                }
              }
            }
          }
        }else{
          printf("\n\nError reading file '%s'.  The first character of each line after the first two lines must be 'R' or 'W'.", fileName);
          return 0;
        }

        if(referenceCounter > numMemRef){
          printf("\n\nError reading file '%s'.  More references in the file than specified by the first line.", fileName);
        }
        referenceCounter++;
      }
      for(int i = 0; i < sizeof(memRef)/sizeof(int); i++){
        printf("%d", memRef[i]);
      }
      return 1;
    }else{
      printf("\n\nError reading file '%s'.  The first line of the input file must be numeric.\n\n", fileName);
      return 0;
    }
  }
}

void printMemoryTable(){

}
int main(){
  for( ; ; ){

    specifyMemorySpecs();

    for( ; ; ){
      int fileReadSuccess = parseFile();
      if(fileReadSuccess){
        break;
      }
    }

    memCalc();

    //printMemoryTable();

    char cont[100];
    for( ; ; ){
      printf("\nContinue? (y = yes, n = no): ");
      scanf("%s", cont);
      printf("\n");
      if(strcmp(cont, "y") != 0 && strcmp(cont, "n") != 0){
        printf("\nError! Please only enter 'y' or 'n'.\n\n");
      }else{
        break;
      }
    }

    if(strcmp(cont, "n") == 0){
      break;
    }

  }
  return 0;
}
